name: linting

on:
  push:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project requirements
        run: pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: flake8 certbot_dns_duckdns --count --ignore E501 --show-source --statistics

      - name: Lint with pylint
        run: pylint certbot_dns_duckdns --disable C0301
